#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v3
# autospec commit: 750e50d
#
Name     : Endeavour
Version  : 43.0
Release  : 3
URL      : https://gitlab.gnome.org/World/Endeavour/-/archive/43.0/Endeavour-43.0.tar.gz
Source0  : https://gitlab.gnome.org/World/Endeavour/-/archive/43.0/Endeavour-43.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: Endeavour-bin = %{version}-%{release}
Requires: Endeavour-data = %{version}-%{release}
Requires: Endeavour-license = %{version}-%{release}
Requires: Endeavour-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gnome-online-accounts-dev
BuildRequires : libpeas-dev
BuildRequires : pkgconfig(goa-1.0)
BuildRequires : pkgconfig(libadwaita-1)
BuildRequires : pkgconfig(libecal-2.0)
BuildRequires : pkgconfig(libpeas-1.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Endeavour
Endeavour is an intuitive and powerful application to manage your personal tasks. It uses GNOME
technologies and has complete integration with the GNOME desktop environment.

%package bin
Summary: bin components for the Endeavour package.
Group: Binaries
Requires: Endeavour-data = %{version}-%{release}
Requires: Endeavour-license = %{version}-%{release}

%description bin
bin components for the Endeavour package.


%package data
Summary: data components for the Endeavour package.
Group: Data

%description data
data components for the Endeavour package.


%package dev
Summary: dev components for the Endeavour package.
Group: Development
Requires: Endeavour-bin = %{version}-%{release}
Requires: Endeavour-data = %{version}-%{release}
Provides: Endeavour-devel = %{version}-%{release}
Requires: Endeavour = %{version}-%{release}

%description dev
dev components for the Endeavour package.


%package doc
Summary: doc components for the Endeavour package.
Group: Documentation

%description doc
doc components for the Endeavour package.


%package license
Summary: license components for the Endeavour package.
Group: Default

%description license
license components for the Endeavour package.


%package locales
Summary: locales components for the Endeavour package.
Group: Default

%description locales
locales components for the Endeavour package.


%prep
%setup -q -n Endeavour-43.0
cd %{_builddir}/Endeavour-43.0
pushd ..
cp -a Endeavour-43.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707075838
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
mkdir -p %{buildroot}/usr/share/package-licenses/Endeavour
cp %{_builddir}/Endeavour-%{version}/COPYING %{buildroot}/usr/share/package-licenses/Endeavour/338650eb7a42dd9bc1f1c6961420f2633b24932d || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang endeavour
## Remove excluded files
rm -f %{buildroot}*/usr/lib64/pkgconfig/endeavour.pc
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/endeavour
/usr/bin/endeavour

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Gtd-1.0.typelib
/usr/share/applications/org.gnome.Todo.desktop
/usr/share/dbus-1/services/org.gnome.Todo.service
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.todo.gschema.xml
/usr/share/icons/hicolor/scalable/apps/org.gnome.Todo.Devel.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Todo.svg
/usr/share/icons/hicolor/symbolic/actions/builder-view-left-pane-symbolic.svg
/usr/share/icons/hicolor/symbolic/actions/drag-handle-symbolic.svg
/usr/share/icons/hicolor/symbolic/actions/mail-inbox-symbolic.svg
/usr/share/icons/hicolor/symbolic/actions/view-tasks-all-symbolic.svg
/usr/share/icons/hicolor/symbolic/actions/view-tasks-today-symbolic.svg
/usr/share/icons/hicolor/symbolic/actions/view-tasks-unscheduled-symbolic.svg
/usr/share/icons/hicolor/symbolic/actions/view-tasks-week-symbolic.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Todo-symbolic.svg
/usr/share/metainfo/org.gnome.Todo.appdata.xml

%files dev
%defattr(-,root,root,-)
/usr/include/endeavour/endeavour.h
/usr/include/endeavour/gtd-activatable.h
/usr/include/endeavour/gtd-animatable.h
/usr/include/endeavour/gtd-animation-utils.h
/usr/include/endeavour/gtd-bin-layout.h
/usr/include/endeavour/gtd-clock.h
/usr/include/endeavour/gtd-easing.h
/usr/include/endeavour/gtd-interval.h
/usr/include/endeavour/gtd-keyframe-transition.h
/usr/include/endeavour/gtd-list-model-filter.h
/usr/include/endeavour/gtd-list-store.h
/usr/include/endeavour/gtd-manager.h
/usr/include/endeavour/gtd-max-size-layout.h
/usr/include/endeavour/gtd-menu-button.h
/usr/include/endeavour/gtd-notification.h
/usr/include/endeavour/gtd-object.h
/usr/include/endeavour/gtd-omni-area-addin.h
/usr/include/endeavour/gtd-omni-area.h
/usr/include/endeavour/gtd-panel.h
/usr/include/endeavour/gtd-property-transition.h
/usr/include/endeavour/gtd-provider-popover.h
/usr/include/endeavour/gtd-provider.h
/usr/include/endeavour/gtd-star-widget.h
/usr/include/endeavour/gtd-task-list-view.h
/usr/include/endeavour/gtd-task-list.h
/usr/include/endeavour/gtd-task.h
/usr/include/endeavour/gtd-timeline.h
/usr/include/endeavour/gtd-transition.h
/usr/include/endeavour/gtd-types.h
/usr/include/endeavour/gtd-utils.h
/usr/include/endeavour/gtd-widget.h
/usr/include/endeavour/gtd-window.h
/usr/include/endeavour/gtd-workspace.h

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/endeavour/add-notes.page
/usr/share/help/C/endeavour/archive.page
/usr/share/help/C/endeavour/assign-color.page
/usr/share/help/C/endeavour/assign-date.page
/usr/share/help/C/endeavour/contributing.page
/usr/share/help/C/endeavour/create-tasklists.page
/usr/share/help/C/endeavour/create-tasks.page
/usr/share/help/C/endeavour/delete-tasklist.page
/usr/share/help/C/endeavour/execute-task.page
/usr/share/help/C/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/C/endeavour/give-star.page
/usr/share/help/C/endeavour/index.page
/usr/share/help/C/endeavour/overview.page
/usr/share/help/C/endeavour/rename-tasklist.page
/usr/share/help/C/endeavour/rename-tasks.page
/usr/share/help/C/endeavour/support.page
/usr/share/help/C/endeavour/switch-theme.page
/usr/share/help/C/endeavour/workflow.page
/usr/share/help/ca/endeavour/add-notes.page
/usr/share/help/ca/endeavour/archive.page
/usr/share/help/ca/endeavour/assign-color.page
/usr/share/help/ca/endeavour/assign-date.page
/usr/share/help/ca/endeavour/contributing.page
/usr/share/help/ca/endeavour/create-tasklists.page
/usr/share/help/ca/endeavour/create-tasks.page
/usr/share/help/ca/endeavour/delete-tasklist.page
/usr/share/help/ca/endeavour/execute-task.page
/usr/share/help/ca/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/ca/endeavour/give-star.page
/usr/share/help/ca/endeavour/index.page
/usr/share/help/ca/endeavour/overview.page
/usr/share/help/ca/endeavour/rename-tasklist.page
/usr/share/help/ca/endeavour/rename-tasks.page
/usr/share/help/ca/endeavour/support.page
/usr/share/help/ca/endeavour/switch-theme.page
/usr/share/help/ca/endeavour/workflow.page
/usr/share/help/cs/endeavour/add-notes.page
/usr/share/help/cs/endeavour/archive.page
/usr/share/help/cs/endeavour/assign-color.page
/usr/share/help/cs/endeavour/assign-date.page
/usr/share/help/cs/endeavour/contributing.page
/usr/share/help/cs/endeavour/create-tasklists.page
/usr/share/help/cs/endeavour/create-tasks.page
/usr/share/help/cs/endeavour/delete-tasklist.page
/usr/share/help/cs/endeavour/execute-task.page
/usr/share/help/cs/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/cs/endeavour/give-star.page
/usr/share/help/cs/endeavour/index.page
/usr/share/help/cs/endeavour/overview.page
/usr/share/help/cs/endeavour/rename-tasklist.page
/usr/share/help/cs/endeavour/rename-tasks.page
/usr/share/help/cs/endeavour/support.page
/usr/share/help/cs/endeavour/switch-theme.page
/usr/share/help/cs/endeavour/workflow.page
/usr/share/help/da/endeavour/add-notes.page
/usr/share/help/da/endeavour/archive.page
/usr/share/help/da/endeavour/assign-color.page
/usr/share/help/da/endeavour/assign-date.page
/usr/share/help/da/endeavour/contributing.page
/usr/share/help/da/endeavour/create-tasklists.page
/usr/share/help/da/endeavour/create-tasks.page
/usr/share/help/da/endeavour/delete-tasklist.page
/usr/share/help/da/endeavour/execute-task.page
/usr/share/help/da/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/da/endeavour/give-star.page
/usr/share/help/da/endeavour/index.page
/usr/share/help/da/endeavour/overview.page
/usr/share/help/da/endeavour/rename-tasklist.page
/usr/share/help/da/endeavour/rename-tasks.page
/usr/share/help/da/endeavour/support.page
/usr/share/help/da/endeavour/switch-theme.page
/usr/share/help/da/endeavour/workflow.page
/usr/share/help/de/endeavour/add-notes.page
/usr/share/help/de/endeavour/archive.page
/usr/share/help/de/endeavour/assign-color.page
/usr/share/help/de/endeavour/assign-date.page
/usr/share/help/de/endeavour/contributing.page
/usr/share/help/de/endeavour/create-tasklists.page
/usr/share/help/de/endeavour/create-tasks.page
/usr/share/help/de/endeavour/delete-tasklist.page
/usr/share/help/de/endeavour/execute-task.page
/usr/share/help/de/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/de/endeavour/give-star.page
/usr/share/help/de/endeavour/index.page
/usr/share/help/de/endeavour/overview.page
/usr/share/help/de/endeavour/rename-tasklist.page
/usr/share/help/de/endeavour/rename-tasks.page
/usr/share/help/de/endeavour/support.page
/usr/share/help/de/endeavour/switch-theme.page
/usr/share/help/de/endeavour/workflow.page
/usr/share/help/es/endeavour/add-notes.page
/usr/share/help/es/endeavour/archive.page
/usr/share/help/es/endeavour/assign-color.page
/usr/share/help/es/endeavour/assign-date.page
/usr/share/help/es/endeavour/contributing.page
/usr/share/help/es/endeavour/create-tasklists.page
/usr/share/help/es/endeavour/create-tasks.page
/usr/share/help/es/endeavour/delete-tasklist.page
/usr/share/help/es/endeavour/execute-task.page
/usr/share/help/es/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/es/endeavour/give-star.page
/usr/share/help/es/endeavour/index.page
/usr/share/help/es/endeavour/overview.page
/usr/share/help/es/endeavour/rename-tasklist.page
/usr/share/help/es/endeavour/rename-tasks.page
/usr/share/help/es/endeavour/support.page
/usr/share/help/es/endeavour/switch-theme.page
/usr/share/help/es/endeavour/workflow.page
/usr/share/help/eu/endeavour/add-notes.page
/usr/share/help/eu/endeavour/archive.page
/usr/share/help/eu/endeavour/assign-color.page
/usr/share/help/eu/endeavour/assign-date.page
/usr/share/help/eu/endeavour/contributing.page
/usr/share/help/eu/endeavour/create-tasklists.page
/usr/share/help/eu/endeavour/create-tasks.page
/usr/share/help/eu/endeavour/delete-tasklist.page
/usr/share/help/eu/endeavour/execute-task.page
/usr/share/help/eu/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/eu/endeavour/give-star.page
/usr/share/help/eu/endeavour/index.page
/usr/share/help/eu/endeavour/overview.page
/usr/share/help/eu/endeavour/rename-tasklist.page
/usr/share/help/eu/endeavour/rename-tasks.page
/usr/share/help/eu/endeavour/support.page
/usr/share/help/eu/endeavour/switch-theme.page
/usr/share/help/eu/endeavour/workflow.page
/usr/share/help/id/endeavour/add-notes.page
/usr/share/help/id/endeavour/archive.page
/usr/share/help/id/endeavour/assign-color.page
/usr/share/help/id/endeavour/assign-date.page
/usr/share/help/id/endeavour/contributing.page
/usr/share/help/id/endeavour/create-tasklists.page
/usr/share/help/id/endeavour/create-tasks.page
/usr/share/help/id/endeavour/delete-tasklist.page
/usr/share/help/id/endeavour/execute-task.page
/usr/share/help/id/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/id/endeavour/give-star.page
/usr/share/help/id/endeavour/index.page
/usr/share/help/id/endeavour/overview.page
/usr/share/help/id/endeavour/rename-tasklist.page
/usr/share/help/id/endeavour/rename-tasks.page
/usr/share/help/id/endeavour/support.page
/usr/share/help/id/endeavour/switch-theme.page
/usr/share/help/id/endeavour/workflow.page
/usr/share/help/ko/endeavour/add-notes.page
/usr/share/help/ko/endeavour/archive.page
/usr/share/help/ko/endeavour/assign-color.page
/usr/share/help/ko/endeavour/assign-date.page
/usr/share/help/ko/endeavour/contributing.page
/usr/share/help/ko/endeavour/create-tasklists.page
/usr/share/help/ko/endeavour/create-tasks.page
/usr/share/help/ko/endeavour/delete-tasklist.page
/usr/share/help/ko/endeavour/execute-task.page
/usr/share/help/ko/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/ko/endeavour/give-star.page
/usr/share/help/ko/endeavour/index.page
/usr/share/help/ko/endeavour/overview.page
/usr/share/help/ko/endeavour/rename-tasklist.page
/usr/share/help/ko/endeavour/rename-tasks.page
/usr/share/help/ko/endeavour/support.page
/usr/share/help/ko/endeavour/switch-theme.page
/usr/share/help/ko/endeavour/workflow.page
/usr/share/help/nl/endeavour/add-notes.page
/usr/share/help/nl/endeavour/archive.page
/usr/share/help/nl/endeavour/assign-color.page
/usr/share/help/nl/endeavour/assign-date.page
/usr/share/help/nl/endeavour/contributing.page
/usr/share/help/nl/endeavour/create-tasklists.page
/usr/share/help/nl/endeavour/create-tasks.page
/usr/share/help/nl/endeavour/delete-tasklist.page
/usr/share/help/nl/endeavour/execute-task.page
/usr/share/help/nl/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/nl/endeavour/give-star.page
/usr/share/help/nl/endeavour/index.page
/usr/share/help/nl/endeavour/overview.page
/usr/share/help/nl/endeavour/rename-tasklist.page
/usr/share/help/nl/endeavour/rename-tasks.page
/usr/share/help/nl/endeavour/support.page
/usr/share/help/nl/endeavour/switch-theme.page
/usr/share/help/nl/endeavour/workflow.page
/usr/share/help/pt_BR/endeavour/add-notes.page
/usr/share/help/pt_BR/endeavour/archive.page
/usr/share/help/pt_BR/endeavour/assign-color.page
/usr/share/help/pt_BR/endeavour/assign-date.page
/usr/share/help/pt_BR/endeavour/contributing.page
/usr/share/help/pt_BR/endeavour/create-tasklists.page
/usr/share/help/pt_BR/endeavour/create-tasks.page
/usr/share/help/pt_BR/endeavour/delete-tasklist.page
/usr/share/help/pt_BR/endeavour/execute-task.page
/usr/share/help/pt_BR/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/pt_BR/endeavour/give-star.page
/usr/share/help/pt_BR/endeavour/index.page
/usr/share/help/pt_BR/endeavour/overview.page
/usr/share/help/pt_BR/endeavour/rename-tasklist.page
/usr/share/help/pt_BR/endeavour/rename-tasks.page
/usr/share/help/pt_BR/endeavour/support.page
/usr/share/help/pt_BR/endeavour/switch-theme.page
/usr/share/help/pt_BR/endeavour/workflow.page
/usr/share/help/ru/endeavour/add-notes.page
/usr/share/help/ru/endeavour/archive.page
/usr/share/help/ru/endeavour/assign-color.page
/usr/share/help/ru/endeavour/assign-date.page
/usr/share/help/ru/endeavour/contributing.page
/usr/share/help/ru/endeavour/create-tasklists.page
/usr/share/help/ru/endeavour/create-tasks.page
/usr/share/help/ru/endeavour/delete-tasklist.page
/usr/share/help/ru/endeavour/execute-task.page
/usr/share/help/ru/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/ru/endeavour/give-star.page
/usr/share/help/ru/endeavour/index.page
/usr/share/help/ru/endeavour/overview.page
/usr/share/help/ru/endeavour/rename-tasklist.page
/usr/share/help/ru/endeavour/rename-tasks.page
/usr/share/help/ru/endeavour/support.page
/usr/share/help/ru/endeavour/switch-theme.page
/usr/share/help/ru/endeavour/workflow.page
/usr/share/help/sv/endeavour/add-notes.page
/usr/share/help/sv/endeavour/archive.page
/usr/share/help/sv/endeavour/assign-color.page
/usr/share/help/sv/endeavour/assign-date.page
/usr/share/help/sv/endeavour/contributing.page
/usr/share/help/sv/endeavour/create-tasklists.page
/usr/share/help/sv/endeavour/create-tasks.page
/usr/share/help/sv/endeavour/delete-tasklist.page
/usr/share/help/sv/endeavour/execute-task.page
/usr/share/help/sv/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/sv/endeavour/give-star.page
/usr/share/help/sv/endeavour/index.page
/usr/share/help/sv/endeavour/overview.page
/usr/share/help/sv/endeavour/rename-tasklist.page
/usr/share/help/sv/endeavour/rename-tasks.page
/usr/share/help/sv/endeavour/support.page
/usr/share/help/sv/endeavour/switch-theme.page
/usr/share/help/sv/endeavour/workflow.page
/usr/share/help/uk/endeavour/add-notes.page
/usr/share/help/uk/endeavour/archive.page
/usr/share/help/uk/endeavour/assign-color.page
/usr/share/help/uk/endeavour/assign-date.page
/usr/share/help/uk/endeavour/contributing.page
/usr/share/help/uk/endeavour/create-tasklists.page
/usr/share/help/uk/endeavour/create-tasks.page
/usr/share/help/uk/endeavour/delete-tasklist.page
/usr/share/help/uk/endeavour/execute-task.page
/usr/share/help/uk/endeavour/figures/org.gnome.Todo.svg
/usr/share/help/uk/endeavour/give-star.page
/usr/share/help/uk/endeavour/index.page
/usr/share/help/uk/endeavour/overview.page
/usr/share/help/uk/endeavour/rename-tasklist.page
/usr/share/help/uk/endeavour/rename-tasks.page
/usr/share/help/uk/endeavour/support.page
/usr/share/help/uk/endeavour/switch-theme.page
/usr/share/help/uk/endeavour/workflow.page

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Endeavour/338650eb7a42dd9bc1f1c6961420f2633b24932d

%files locales -f endeavour.lang
%defattr(-,root,root,-)

